//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-661 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.05.20 at 11:22:47 ÉÏÎç CST 
//


package com.dvn.sys.dass.sms.po.basequery.response;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ReturnCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ReturnMsg" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="BaseAccount" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ServiceData" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Paying" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Isornot" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "returnCode",
    "returnMsg",
    "baseAccount",
    "serviceData",
    "paying",
    "isornot"
})
@XmlRootElement(name = "SMSBaseQueryAPI-Response")
public class SMSBaseQueryAPIResponse {

    @XmlElement(name = "ReturnCode", required = true)
    protected String returnCode;
    @XmlElement(name = "ReturnMsg", required = true)
    protected String returnMsg;
    @XmlElement(name = "BaseAccount", required = true)
    protected String baseAccount;
    @XmlElement(name = "ServiceData", required = true)
    protected String serviceData;
    @XmlElement(name = "Paying", required = true)
    protected String paying;
    @XmlElement(name = "Isornot", required = true)
    protected String isornot;

    /**
     * Gets the value of the returnCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReturnCode() {
        return returnCode;
    }

    /**
     * Sets the value of the returnCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReturnCode(String value) {
        this.returnCode = value;
    }

    /**
     * Gets the value of the returnMsg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReturnMsg() {
        return returnMsg;
    }

    /**
     * Sets the value of the returnMsg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReturnMsg(String value) {
        this.returnMsg = value;
    }

    /**
     * Gets the value of the baseAccount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBaseAccount() {
        return baseAccount;
    }

    /**
     * Sets the value of the baseAccount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBaseAccount(String value) {
        this.baseAccount = value;
    }

    /**
     * Gets the value of the serviceData property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceData() {
        return serviceData;
    }

    /**
     * Sets the value of the serviceData property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceData(String value) {
        this.serviceData = value;
    }

    /**
     * Gets the value of the paying property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaying() {
        return paying;
    }

    /**
     * Sets the value of the paying property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaying(String value) {
        this.paying = value;
    }

    /**
     * Gets the value of the isornot property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsornot() {
        return isornot;
    }

    /**
     * Sets the value of the isornot property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsornot(String value) {
        this.isornot = value;
    }

}
